/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-first-pet`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pets/add`; params?: Router.UnknownInputParams; } | { pathname: `/pets`; params?: Router.UnknownInputParams; } | { pathname: `/pets/[petId]/edit`, params: Router.UnknownInputParams & { petId: string | number; } } | { pathname: `/pets/[petId]`, params: Router.UnknownInputParams & { petId: string | number; } } | { pathname: `/pets/[petId]/records/[recordId]`, params: Router.UnknownInputParams & { petId: string | number;recordId: string | number; } } | { pathname: `/pets/[petId]/records/add`, params: Router.UnknownInputParams & { petId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/add-first-pet`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/pets/add`; params?: Router.UnknownOutputParams; } | { pathname: `/pets`; params?: Router.UnknownOutputParams; } | { pathname: `/pets/[petId]/edit`, params: Router.UnknownOutputParams & { petId: string; } } | { pathname: `/pets/[petId]`, params: Router.UnknownOutputParams & { petId: string; } } | { pathname: `/pets/[petId]/records/[recordId]`, params: Router.UnknownOutputParams & { petId: string;recordId: string; } } | { pathname: `/pets/[petId]/records/add`, params: Router.UnknownOutputParams & { petId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/add-first-pet${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/pets/add${`?${string}` | `#${string}` | ''}` | `/pets${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/add-first-pet`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pets/add`; params?: Router.UnknownInputParams; } | { pathname: `/pets`; params?: Router.UnknownInputParams; } | `/pets/${Router.SingleRoutePart<T>}/edit${`?${string}` | `#${string}` | ''}` | `/pets/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/pets/${Router.SingleRoutePart<T>}/records/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/pets/${Router.SingleRoutePart<T>}/records/add${`?${string}` | `#${string}` | ''}` | { pathname: `/pets/[petId]/edit`, params: Router.UnknownInputParams & { petId: string | number; } } | { pathname: `/pets/[petId]`, params: Router.UnknownInputParams & { petId: string | number; } } | { pathname: `/pets/[petId]/records/[recordId]`, params: Router.UnknownInputParams & { petId: string | number;recordId: string | number; } } | { pathname: `/pets/[petId]/records/add`, params: Router.UnknownInputParams & { petId: string | number; } };
    }
  }
}
